// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using BasicBot.GraphQL.SetsAndLinkedAccounts;
//
//    var setsAndLinkedAccounts = SetsAndLinkedAccounts.FromJson(jsonString);

namespace BasicBot.GraphQL.SetsAndLinkedAccounts
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SetsAndLinkedAccounts
    {
        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("extensions")]
        public Extensions Extensions { get; set; }

        [JsonProperty("actionRecords")]
        public List<object> ActionRecords { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("currentUser")]
        public CurrentUser CurrentUser { get; set; }

        [JsonProperty("event")]
        public Event Event { get; set; }
    }

    public partial class CurrentUser
    {
        [JsonProperty("id")]
        public long Id { get; set; }
    }

    public partial class Event
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("tournament")]
        public Tournament Tournament { get; set; }

        [JsonProperty("sets")]
        public Sets Sets { get; set; }
    }

    public partial class Sets
    {
        [JsonProperty("nodes")]
        public List<Node> Nodes { get; set; }
    }

    public partial class Node
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("totalGames")]
        public long TotalGames { get; set; }

        [JsonProperty("state")]
        public long State { get; set; }

        [JsonProperty("games")]
        public List<Game> Games { get; set; }

        [JsonProperty("slots")]
        public List<Slot> Slots { get; set; }
    }

    public partial class Game
    {
        [JsonProperty("winnerId")]
        public long WinnerId { get; set; }

        [JsonProperty("orderNum")]
        public long OrderNum { get; set; }

        [JsonProperty("stage")]
        public object Stage { get; set; }
    }

    public partial class Slot
    {
        [JsonProperty("entrant")]
        public Entrant Entrant { get; set; }
    }

    public partial class Entrant
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("participants")]
        public List<Participant> Participants { get; set; }
    }

    public partial class Participant
    {
        [JsonProperty("gamerTag")]
        public string GamerTag { get; set; }

        [JsonProperty("requiredConnections")]
        public List<RequiredConnection> RequiredConnections { get; set; }
    }

    public partial class RequiredConnection
    {
        [JsonProperty("id")]
        public object Id { get; set; }

        [JsonProperty("externalId")]
        public string ExternalId { get; set; }

        [JsonProperty("externalUsername")]
        public string ExternalUsername { get; set; }

        [JsonProperty("type")]
        public TypeEnum Type { get; set; }

        [JsonProperty("url")]
        public object Url { get; set; }
    }

    public partial class Tournament
    {
        [JsonProperty("admins")]
        public List<CurrentUser> Admins { get; set; }
    }

    public partial class Extensions
    {
        [JsonProperty("cacheControl")]
        public CacheControl CacheControl { get; set; }

        [JsonProperty("queryComplexity")]
        public long QueryComplexity { get; set; }
    }

    public partial class CacheControl
    {
        [JsonProperty("version")]
        public long Version { get; set; }

        [JsonProperty("hints")]
        public List<Hint> Hints { get; set; }
    }

    public partial class Hint
    {
        [JsonProperty("path")]
        public List<string> Path { get; set; }

        [JsonProperty("maxAge")]
        public long MaxAge { get; set; }

        [JsonProperty("scope")]
        public string Scope { get; set; }
    }

    public enum TypeEnum { 
        Twitter,
        Twitch,
        Steam,
        Discord,
        Xbox,
        Mixer 
    };

    public partial class SetsAndLinkedAccounts
    {
        public static SetsAndLinkedAccounts FromJson(string json) => JsonConvert.DeserializeObject<SetsAndLinkedAccounts>(json, BasicBot.GraphQL.SetsAndLinkedAccounts.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this SetsAndLinkedAccounts self) => JsonConvert.SerializeObject(self, BasicBot.GraphQL.SetsAndLinkedAccounts.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                TypeEnumConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "TWITTER")
            {
                return TypeEnum.Twitter;
            }
            if (value == "TWITCH")
            {
                return TypeEnum.Twitch;
            }
            if (value == "STEAM")
            {
                return TypeEnum.Steam;
            }
            if (value == "DISCORD")
            {
                return TypeEnum.Discord;
            }
            if (value == "XBOX")
            {
                return TypeEnum.Xbox;
            }
            if (value == "MIXER")
            {
                return TypeEnum.Mixer;
            }
            
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            if (value == TypeEnum.Twitter)
            {
                serializer.Serialize(writer, "TWITTER");
                return;
            }
            if (value == TypeEnum.Twitch)
            {
                serializer.Serialize(writer, "TWITCH");
                return;
            }
            if (value == TypeEnum.Steam)
            {
                serializer.Serialize(writer, "STEAM");
                return;
            }
            if (value == TypeEnum.Discord)
            {
                serializer.Serialize(writer, "DISCORD");
                return;
            }
            if (value == TypeEnum.Xbox)
            {
                serializer.Serialize(writer, "XBOX");
                return;
            }
            if (value == TypeEnum.Mixer)
            {
                serializer.Serialize(writer, "MIXER");
                return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }
}
